include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Consistency
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_constructors_first: true
    prefer_final_fields: true
    always_declare_return_types: true
    
    # Safety
    cancel_subscriptions: true
    close_sinks: true
    avoid_print: false # Allowed for this package
    
    # Best Practices
    public_member_api_docs: true # Good for published packages
    
    # Style
    prefer_single_quotes: true
    unnecessary_this: true
    annotate_overrides: true
    avoid_function_literals_in_foreach_calls: false
